# Generated by Django 5.0.7 on 2024-07-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="slug"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Содержимое"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product/photo",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "publication",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "number_of_views",
                    models.IntegerField(default=0, verbose_name="Просмотры"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
